version: '3'
services:
  press-serve:
    build: .
    container_name: press-serve
    volumes:
      - ./tmp:/app/tmp
    restart: on-failure
    expose:
      - 4000
    env_file:
      - env
    networks:
      pressnet:
        ipv4_address: 10.1.0.101
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./ssl/advpls.com.pem:/etc/ssl/advpls.com.pem
      - ./ssl/advpls.com.key:/etc/ssl/advpls.com.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      pressnet:
        ipv4_address: 10.1.0.102
networks:
  pressnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
