version: '3'
services:
  npapi:
    build: .
    container_name: npapi
    volumes:
      - ./tmp:/app/tmp
    expose:
      - 4000
    env_file:
      - env
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./ssl/advpls.com.pem:/etc/ssl/advpls.com.pem
      - ./ssl/advpls.com.key:/etc/ssl/advpls.com.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
